# Generated by Django 4.2.3 on 2023-08-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscore',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
