# Generated by Django 4.2.3 on 2023-08-04 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_highscore_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizhistory',
            options={'verbose_name_plural': 'Quiz Histories'},
        ),
    ]
