# Generated by Django 4.2.3 on 2023-08-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_quizhistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizhistory',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
